.PHONY: all build clean run test

all: build

build:
	cargo build --manifest-path Cargo.toml

clean:
	cargo clean --manifest-path Cargo.toml

run:
	cargo run --manifest-path Cargo.toml

test:
	cargo test --manifest-path Cargo.toml
